console.log("Muneeb Shahid");
console.log("salman shah");
console.log("AHMED");
console.log("ali");
console.log("sufyan");
console.log('abdullah');
console.log('mehran');
console.log('ahyan');
console.log('farham');
console.log('shehroz');
console.log('Hello World');
console.log('control and measurement block');
console.log('HF Circuit of UHF Band Receiver');
console.log('Servo Amplifier Spada');
console.log('Ind Dev of Anti Dome Display of JF-17A Blk - II');
console.log("AHQ");
console.log("free Fall Training Simulator");
console.log("Dental Simulator");
console.log("Generic Integrated Training Branch");
let id = 1001;
let id1 = 1005;
let id2 = 1006;
let id3 = 1011;
let id4 = 5000;
console.log(id1 + id2 + id3 + id4); 
console.log(id1 - id2 - id3 - id4); 
console.log(id1 * id2); 
console.log(id1 / id2); 
console.log(id1 % id2); 
let myname = "Muneeb shahid";
myname = "shujjat mehboob";
myname = 'ahsan';
let message = "he is a good person and hardworking";
console.log(myname , message); 
let word = "hello world";
let sample = "switzerland";
console.log(word , sample);

